from builtins import Exception


class UnknownError(Exception):
    pass